import Head from "next/head"
import { fetchGraphQL } from "@/utils/contentful"
import { queries } from '@/utils/query'
import { useState, useEffect } from "react"
import styles from '@/styles/Home.module.css'
import Image from "next/image"
import defaultImg from '@/public/images/default.jpg'
import { useRouter } from "next/router";
import ModalOverlay from '@/components/modal-overlay'

export default function Home() {

  const [thoughts, setThoughts] = useState(null)
  const [ideas, setIdeas] = useState(null)

  const [modalState, setModalState] = useState({
    isOpen: false,
    contentSlug: ''
  })

  const changeModalState = (isOpen, slug) => setModalState({ isOpen, contentSlug: slug })

  const cloud = 'cloud'

  useEffect(() => {
    fetchGraphQL(`{ ${queries.thoughts}, ${queries.ideas} }`)
      .then((content) => {
        const data = content.data
        setThoughts(data.blogPostCollection.items)
        setIdeas(data.ideaCollection.items)

        const routeParams = window.location.search
        routeParams.includes(cloud) && changeModalState(true, routeParams.split('=')[1])
        //split the search location params to look sth like ['?cloud', 'a-post-slug'] then take the slug obvs
      })

    return () => {}
  }, [])

  const cloudTopPositions = [10,20,30,40,50,60,70]
  const router = useRouter()

  return (
    <>
    <Head>
        <title>uzomas.garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id='garden'>
        <div id='sky'>
          {
            thoughts && thoughts.map(({slug, title}, index) => 
                <div className={styles.cloud} key={slug} style={{
                    animationDelay: `${index*10}s`,
                    top: `${cloudTopPositions[Math.floor(Math.random()*cloudTopPositions.length)]}px`
                  }} onClick={() => {
                    changeModalState(true, slug)
                    router.push(`/?${cloud}=${slug}`, undefined, { shallow: true })
                  }}>
                  <h3 className={styles.title}>{title}</h3>
                </div>
            )
          }
        </div>
        <div id='ground' className={styles.ideas}>
          {
            ideas && ideas.map(({ title, imagesCollection, date }, index) => {
              const image = imagesCollection.items[0]
              return <div key={index} className={styles.idea}>
                <Image 
                  src={ image ? image.url : defaultImg } 
                  alt={ image ? image.fileName : "default image" }
                  width={100} 
                  height={100} 
                />
                <p>{title}</p>
                <small>{date}</small>
              </div>
            })
          }
        </div>
        { modalState.isOpen && 
          <ModalOverlay 
            postContent={thoughts.filter(({ slug }) => slug === modalState.contentSlug)[0]} 
            setModalState={setModalState}
          /> 
        }
      </main>
    </>
  )
}
